FROM node:18-alpine as helpr-api

ARG DATABASE_URL
ARG MAILER_HOST
ARG MAILER_PORT
ARG MAILER_USER
ARG MAILER_PASSWORD
ARG AUTH_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG AUTH_TOKEN_EXPIRATION
ARG REFRESH_TOKEN_EXPIRATION
ARG STRIPE_SECRET_KEY
ARG FRONTEND_URL
ARG APP_ENV
ARG API_URL
ARG GOOGLE_CLIENT_ID
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GITHUB_CALLBACK_URL
ARG LINEAR_CLIENT_ID
ARG LINEAR_CLIENT_SECRET
ARG LINEAR_CALLBACK_URL
ARG LINKEDIN_CLIENT_ID
ARG LINKEDIN_CLIENT_SECRET
ARG LINKEDIN_CALLBACK_URL
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG LINEAR_API_KEY
ARG OPENAI_API_KEY
ARG DEEPL_API_KEY

COPY . .

RUN npm install --force

RUN npm run build

RUN npx prisma generate

CMD ["npm", "start"]

EXPOSE 3000